ID <- c(1,2,3,4)
age <- c(23,52,62,24)
type <- c("Type1","Type2","Type1","Type1")
status <- c("poor","improved","excellent","poor")
type <- factor(type)
status <- factor(status,order=TRUE)
data <- data.frame(ID,age,type,status)
str(data)
summary(data)
